# .gitlab-ci.yml

# Utilisation de l'image Docker contenant Node.js pour la construction du projet
image: node:latest

# Stages du pipeline CI/CD
stages:
  - build
  - deploy

# Définition des tâches à exécuter dans chaque stage
build:
  stage: build
  script:
    - npm install -g @angular/cli   # Installer Angular CLI globalement
    - npm install    # Installer les dépendances
    - ng build --configuration=production   # Construire l'application Angular en mode production

# Déploiement sur GitLab Pages
deploy:
  stage: deploy
  script:
    - mv dist/esport-simplon/* public/  # Déplacer les fichiers construits dans un répertoire public
    - ls -l public/    # Vérifier que les fichiers sont bien présents (facultatif)
  artifacts:
    paths:
      - public/   # Spécifier le répertoire à déployer
    expire_in: 1 week
  only:
    - main  # Déployer uniquement lorsque la branche main est mise à jour
  environment:
    name: production
  pages:
    script:
      - mkdir .public  # Créer un répertoire pour le déploiement
      - cp -r * .public  # Copier tous les fichiers à déployer dans ce répertoire
      - mv .public public  # Renommer le répertoire pour le rendre accessible à Pages
    artifacts:
      paths:
        - public  # Spécifier le répertoire à déployer
    only:
      - main  # Déployer uniquement lorsque la branche main est mise à jour
